### ISSUE TITLE
Login PW not accepted and Error 500 when trying to change PW on SWSheets account

### ISSUE THREAD

**Issue by ShadowSix5474** [swsheets/blog#6]

**Comment by duffn** [comment]
Hello, can you please tell me your username on SWSheets? Is it the same as here?

**Comment by ShadowSix5474** [comment]
ShadowSix

**Comment by ShadowSix5474** [comment]
Any new developments?

**Comment by ShadowSix5474** [comment]
@duffn , haven't heard back from you on this issue in a while.

**Comment by duffn** [comment]
Seem to be having some difficulty with emails from the app. I’ve sent you a manual reset link in the meantime. Please let me know if that works.

**Comment by duffn** [comment]
I believe I've fixed this on the site now. Thanks for the heads up.

**Comment by ShadowSix5474** [comment]
Thankyou for your assistance

**Comment by duffn** [comment]
Thanks for using the site!
